---
apiVersion: v1
kind: Service
metadata:
  name: cast-info-mongodb
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: cast-info-mongodb
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: media-microsvc
    app-name: cast-info-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-info-mongodb
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: cast-info-mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: cast-info-mongodb
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: cast-info-mongodb
      name: cast-info-mongodb
    spec:
      containers:
      - name: cast-info-mongodb
        image: mongo
        resources:
          limits:
            memory: "675Mi"
            cpu: "300m"
          requests:
            memory: "675Mi"
            cpu: "300m"
      restartPolicy: Always