---
apiVersion: v1
kind: Service
metadata:
  name: compose-review-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: compose-review-service
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: media-microsvc
    app-name: compose-review-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-review-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: compose-review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: compose-review-service
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: compose-review-service
      name: compose-review-service
    spec:
      containers:
      - name: compose-review-service
        image: yg397/media-microservices
        command: ["ComposeReviewService"]
        resources:
          limits:
            memory: "47Mi"
            cpu: "300m"
          requests:
            memory: "47Mi"
            cpu: "300m"
      restartPolicy: Always
