apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: movie-review-redis-vpa
  namespace: media-microsvc
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       movie-review-redis
  updatePolicy:
    updateMode: "Auto"