---
apiVersion: v1
kind: Service
metadata:
  name: movie-review-redis
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: movie-review-redis
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: media-microsvc
    app-name: movie-review-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-review-redis
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: movie-review-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: movie-review-redis
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: movie-review-redis
      name: movie-review-redis
    spec:
      containers:
      - name: movie-review-redis
        image: redis
        resources:
          limits:
            memory: "38Mi"
            cpu: "300m"
          requests:
            memory: "38Mi"
            cpu: "300m"
      restartPolicy: Always
