apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-web-server-vpa
  namespace: media-microsvc
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       nginx-web-server
  updatePolicy:
    updateMode: "Auto"