apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rating-redis-vpa
  namespace: media-microsvc
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       rating-redis
  updatePolicy:
    updateMode: "Auto"