apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: user-memcached-vpa
  namespace: media-microsvc
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       user-memcached
  updatePolicy:
    updateMode: "Auto"