---
apiVersion: v1
kind: Service
metadata:
  name: unique-id-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: unique-id-service
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: media-microsvc
    app-name: unique-id-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unique-id-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: unique-id-service
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: unique-id-service
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: unique-id-service
      name: unique-id-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodeval
                    operator: In
                    values:
                      - n1
      containers:
      - name: unique-id-service
        image: yg397/media-microservices
        command: ["UniqueIdService"]
      restartPolicy: Always
